### ISSUE TITLE
Question: is there a reason why the configuration is not using overrides?

### ISSUE THREAD

**Issue by marcuschangarm** [ARMmbed/easy-connect#48] opened 2017-10-13 15:53 UTC
At the moment we are configuring network settings like this:

```
    "config": {
        "network-interface":{
            "help": "Options are ETHERNET, WIFI_ESP8266, WIFI_ODIN",
            "value": ""
        },
        "wifi-ssid": {
            "help": "WiFi SSID",
            "value": "\"\""
        },
        "wifi-password": {
            "help": "WiFi Password",
            "value": "\"\""
        }
    }
```

Which gets turned into MBED_CONF_APP_NETWORK_INTERFACE etc. 

However, if we defined a namespace in mbed_lib.json (similar to how it is done in the sd-driver https://github.com/ARMmbed/sd-driver/blob/master/config/mbed_lib.json#L2) then defines would look like this instead: MBED_CONF_EASY_CONNECT_NETWORK_INTERFACE.

The benefit of doing it this way is that users can now use the `target_overrides` feature to support multiple boards in a single mbed_app.json, for example:

```
    "target_overrides": {
        "*": {
            "easy-connect.network-ssid": "",
            "easy-connect.network-password": ""
        },
        "K64F": {
            "easy-connect.network-interface": "ETHERNET"
        },
        "NUCLEO_F429ZI": {
            "easy-connect.network-interface": "ETHERNET"
        },
        "UBLOX_EVK_ODIN_W2": {
            "easy-connect.network-interface": "WIFI_ODIN"
        }
    },
```

Is there a reason for not doing the latter, and would there be any objections if I submit a backwards compatible PR that enables overrides?

**Comment by JanneKiiskila** [comment] 2017-10-15 13:08
@janjongboom should comment on this, since he's the original author of the easy-connect. From my point of view - I can't see any major blockers, why not but wiser men should comment. Like @anttiylitokola, @teetak01  and @TeroJaasko .

Sounds good, especially if we can maintain back-wards compatibility.

I think we already now can support multiple boards with one `mbed_app.json` but it's then based on we have one json file per networking.

**Comment by marcuschangarm** [comment] 2017-10-15 14:12
>Sounds good, especially if we can maintain back-wards compatibility.

My plan was something really simple:

```
#ifndef MBED_CONF_APP_NETWORK_INTERFACE 
#define MBED_CONF_APP_NETWORK_INTERFACE MBED_CONF_EASY_CONNECT_NETWORK_INTERFACE
#endif
```

So if both are defined, the old way will always have higher priority.

**Comment by janjongboom** [comment] 2017-10-16 03:51
@marcuschangarm Yes, there is reason behind it. I did it because:

1. The syntax is ugly. As a user I don't care what 'easy-connect' is. I just want to set my connectivity method. `network-interface` is superior to `easy-connect.network-interface`.
1. Users can see all options directly in mbed_app.json.
1. Target overrides are impossible to discover.
1. With target overrides we cannot add `help` information.
1. Maintaining the mbed_app.json of every app that uses easy-connect will be a PITA because they need to be updated every time a new board comes out.
1. Explaining how to override this stuff becomes harder. Let's say you want to use the ST WiFi shield instead of Ethernet on K64F. Now I can tell you to add a section under `*`, but if your board also has a board target override then this will be ignored again. Right now I can tell you to just change this one setting.
1. What if a board has two connectivity methods (e.g. ODIN), which one do we choose as default?

I do like the idea that easy-connect magically knows which connectivity method your board has, but I do see some points against adding it to target overrides.

**Comment by marcuschangarm** [comment] 2017-10-16 04:12
I don't see why we can't have both? With the suggested implementation above, your configuration will always take precedence over any target overrides. 

At the moment, besides the Odin W2, many of our boards like the K64F, STM32F429, and RTL8195AM have a native network connection. It would be useful if by default the native network connection was selected so the user doesn't have to select anything - isn't that the best user experience?

If a user then wants to use a WIFI board instead, they would do as they do now and add the information to the configuration setting.

**Comment by janjongboom** [comment] 2017-10-16 04:41
> At the moment, besides the Odin W2, many of our boards like the K64F, STM32F429, and RTL8195AM have a native network connection. It would be useful if by default the native network connection was selected so the user doesn't have to select anything - isn't that the best user experience?

Agree.

> I don't see why we can't have both? With the suggested implementation above, your configuration will always take precedence over any target overrides.

Sure. It'd make some things easier. If we can properly fall back that'd work.

**Comment by kjbracey** [comment] 2017-10-16 07:32
From the networking point of view our aim for the future is to reduce the need for things like easy-connect, by providing a system way for an application to request the "primary network interface with default configuration".

That would mean having a system/target way of controlling what that primary interface (and settings) are, for boards where that is necessary.

I think that would end up ultimately working similarly to Marcus's proposal - boards would have a default primary interface, and applications could use an alternative by using a JSON setting to get the target to make a different interface the primary. (Also, apps could always manually specify a network interface by naming a class or passing appropriate constructor parameters, and easy-connect could continue to do so).

Any app that did want to modify that JSON setting would have to do it in a `target_overrides` - target-specific if the app was intended to be portable.

I'm guessing it would be `platform.[primary-]network-interface` or similar, alongside `platform.stdio-baud-rate` et al.

What remains an issue is how can we make it easy to flip a default in a target JSON without the need to actually get apps to mess around with needing a local mbed-app.json. I can vaguely envisage something like `mbed compile my-app -m ODIN_W2 -t GCC_ARM --config MyWifi.json`, where that pulls in a bit of extra config flipping default interface to WiFi and specifying my access point. The same system could extend to `--config baud115200.json` or whatever.

Mind you, I agree with Jan that there is something to be said for having everything in "one place" in easy-connect. At the cost of needing knowledge of every board up-front, you do end up with simpler presentation for the user.

**Comment by marcuschangarm** [comment] 2017-10-16 20:40
@kjbracey-arm thank you for the insight, do you have a rough estimate for when this work is scheduled for?

**Comment by kjbracey** [comment] 2017-10-17 06:26
Not before 5.8, I'm afraid. It's part of a large restructuring package to do with EMAC and other bits.

I'm just letting you folks know that there is likely to be future change, and in which direction - I don't want to necessarily preclude changes to easy-connect.

easy-connect would continue to work after the changes I'm talking about anyway - it may not be totally obsoleted if people still preferred the gloss of an "all-settings-in-one-place" manual switcher for their demo apps.

**Comment by kjbracey** [comment] 2017-10-17 06:30
Oh, and the `--config` suggestion I mentioned is just handwaving at this point - it's only the networking that I'm actually planning and working on. But it seems like it might make use of the upcoming networking changes (and other existing config messing) more practical.

Something for those at the pointy end of making configurable demo apps to discuss with the config guys, perhaps.

**Comment by marcuschangarm** [comment] 2017-10-17 14:05
Cool, I'll pull together a PR!

**Comment by teetak01** [comment] 2018-10-17 06:12
Closing as this repository has been deprecated with introduction of new network APIs in Mbed OS 5.10.

**Closed as completed by teetak01** 2018-10-17 06:12 UTC
Labels: enhancement, help wanted
